MVCFilesConvertor/MVCFilesConvertor/Controllers/CSVtoXMLController.cs
using System.Web.Mvc;
using MVCFilesConvertor.Models;
using MVCFilesConvertor.Models.Interfaces;

namespace MVCFilesConvertor.Controllers
{
    public class CSVtoXMLController : Controller
    {
        //Autofac
        private readonly ICSVtoXMLViewModel cSVtoXMLViewModel;

        //Autofac
        public CSVtoXMLController(ICSVtoXMLViewModel iCSVtoXMLViewModel)
        {
            cSVtoXMLViewModel = iCSVtoXMLViewModel;
        }

        // form view for input file
        public ActionResult CSVtoXML()
        {
            return View(cSVtoXMLViewModel);
        }

        // convert of CSV file to XML
        [HttpPost]
        public ActionResult CSVtoXML(CSVtoXMLViewModel cSVtoXMLViewModel)
        {
            if (!ModelState.IsValid)
                return View(cSVtoXMLViewModel);

            string result= cSVtoXMLViewModel.ConvertCSVtoXML(cSVtoXMLViewModel.CSVfile);

            return RedirectToAction("GetOutputFile", "Home", new { result=result});
        }
    }
}

MVCFilesConvertor/MVCFilesConvertor/Controllers/HomeController.cs
using System.Web.Mvc;
using MVCFilesConvertor.Models;

namespace MVCFilesConvertor.Controllers
{
    // offer display 
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        // link display to output file
        public ActionResult GetOutputFile(string result)
        {
            if (result.Contains("Chyba"))
                TempData["Error"] = result;
            else
                TempData["OutputFilePath"] = result; 

            return View();
        }

        // delete of saved files
        public ActionResult DeleteSavedFiles()
        {
            TempData["Deletion"] = WorkingWithInputAndOutputFiles.DeleteSavedFiles();
            return RedirectToAction("Index", "Home");
        }
    }
}

MVCFilesConvertor/MVCFilesConvertor/Views/Home/GetOutputFile.cshtml
@{
    ViewBag.Title = "Output page";
}

<div class="jumbotron">
    <h1>Odkaz na výsledný soubor</h1><br />

    @if (TempData.ContainsKey("OutputFilePath"))
    {
        <p class="lead">Níže je uveden odkaz na výsledný soubor</p>
        <h3>@TempData["OutputFilePath"]</h3>
        @* <a href="@TempData["OutputFilePath"]", class="btn btn-primary btn-lg" download="DataXML.xml">Odkaz ke stažení </a>
           <a href="file:///C:/Users/David/AppData/Roaming/MVCFilesConvertor/DataXML.xml" , class="btn btn-primary btn-lg" download="DataXML.xml">Odkaz ke stažení </a> *@
        <br/>
        @Html.ActionLink("Odstranění složky MVCFilesConvertor včetně souborů z výše uvedené cesty", "DeleteSavedFiles", controllerName: "Home", routeValues: null, htmlAttributes: new { @class = "btn btn-primary btn-lg" })
    }

    @if (TempData.ContainsKey("Error"))
    {
        <p class="lead">@TempData["Error"]</p>

        @Html.ActionLink("z CSV do XML", "CSVtoXML", controllerName: "CSVtoXML", routeValues: null, htmlAttributes: new { @class = "btn btn-primary btn-lg" })

        @Html.ActionLink("Odstranění složky MVCFilesConvertor včetně souborů z výše uvedené cesty", "DeleteSavedFiles", controllerName: "Home", routeValues: null, htmlAttributes: new { @class = "btn btn-primary btn-lg" })
    }

</div>

MVCFilesConvertor/MVCFilesConvertor/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h3>@if (TempData.ContainsKey("Deletion"))
{
    @TempData["Deletion"]
}
</h3>
<div class="jumbotron">
    <h1>Převodník souborů</h1>
    <p class="lead">Převodník souborů umožnuje převést soubor z jednoho formátu do jiného.</p>
    @Html.ActionLink("z CSV do XML", "CSVtoXML", controllerName: "CSVtoXML", routeValues: null, htmlAttributes: new { @class = "btn btn-primary btn-lg" })
    
    
</div>